### ISSUE TITLE
Workflow: simplifying update page

### ISSUE THREAD

**Issue by hadiasghari** [datarights/DataInSight#110]
The AR status update page needs to be simplified for usability reasons. There is currently too many decisions to make on one page, and some of them might be conflicting, as the screenshot shows.

Some suggestions:
- Uploading a response can be moved to a separate button/form (next to the AR history for instance). 
Here we inform the user that they can upload responses later. 
- The ability to edit the response should be taken out of this form as well. (The letter cannot be edited easily anyway)
- Incompatible options can be selected between the two dropdowns; options in the dropwdowns are also not logically ordered (perhaps these can be fixed in the admin panel and with tweaked language?)

![di update page](https://user-images.githubusercontent.com/5025042/37246128-b93ebe1a-24a3-11e8-8dd4-8d8b467aa1a3.png)

**Comment by postdigital** [comment]
I think we might be confusing some UX decisions here with what can be adjusted in the Admin panel, I mean the actions allowed, the use of language etc etc. That can vary per campaign, so we can limit the options or order them differently etc. On the UX side I wanted it to be as flexible as possible... That is also a result of a longer session I had with Mani the other day which lead to a simplification of the 'action-reaction' method of status updating in the workflow. 

It is true that there might be somewhat conflicting or absurd decisions possible... But we count on the intelligence of the user. Do you think, too much? I was discussing with Mani a possibility to limit actions possible/available for specific reactions of the organisations, but this would be a nightmare to do well, as there are always many exceptions. Right now there is a lot of freedom for the user to report things, for good and for bad. I'm reluctant to limit that freedom, at least not at this stage, before testing it with some users.

Regarding your suggestions:

1. The (optional) upload field can be taken out from here, but personally I don't think it's a problem. I do like that everything is in one place. It is efficient this way.

2. There has been a reason why Mani and me added the possibility to edit the letter already in this window. @mani47 correct me if I'm wrong, but this was needed to properly close the status update? Am I correct? Or can that be separated? Again, like mentioned in point 1 above I don't mind everything is done in one window. I personally do like the compactness of that. It is efficient, less clicking, less steps, everything you need on one page. If we disagree on this, I'd say, let's "ask" our test users first and then adapt the design according to their feedback.

3. I have ordered the list a bit better now, and made adjustments in the language. This is possible in the Admin. However I wouldn't know how to determine compatibility or incompatibility of the options in the backend in order to split them between two dropdowns... I'm not saying it is not possible, but I'm afraid we don't have a solution for that in the Admin (yet)? And do we really need that? @mani47 what do you think? 

<img width="786" alt="screen shot 2018-03-13 at 07 16 38" src="https://user-images.githubusercontent.com/436937/37327471-c1a11bee-2696-11e8-9948-455c37a5d35e.png">

**Comment by hadiasghari** [comment]
@postdigital I will check the back-end today. I agree with counting on the user's intelligence. 

However, I have a simple rule of thumb: can I write a simple set of instructions/steps for users? 

When thinking about it with this heuristic, this UX has too many conditionals (ignore this if you're doing X, do this than this if you're doing Y).

**Comment by hadiasghari** [comment]
Closing this. Partially solved by Mani already; partially related to #121
