### ISSUE TITLE
"Awaiting response" strangeness

### ISSUE THREAD

**Issue by hadiasghari** [datarights/DataInSight#111]
The list of options that appear after clicking 'awaiting response' -- which I assume is when the user is waiting for the organization (and thus might hear back from them) is rather strange (see below). 

For instance, instead of "I want to do an update", the user should have the actual list of updates. (Perhaps this is related to the complexity of #110?) "Timeout" also is unclear.

(Please correct me if this is simply a matter of correcting the workflow in the admin.)

![di awaiting response page](https://user-images.githubusercontent.com/5025042/37246224-b7006dea-24a5-11e8-9bca-1a76d366b557.png)

**Comment by postdigital** [comment]
1. With 'I want to do an update' we mean terminating the 'Awaiting response' state, e.g. in case the response has been already received before time out. So I think that is correct. I think it makes sense to first declare the desire to do an update and then specify what exactly has happened, because we can also say that...:

2. 'I don't want to continue'

or 

3. 'Undo' this status (in case we made a mistake)

4. I think that indeed 'Timed out' should be removed from the list, cause that happens automatically. 

@mani47 Regarding point 3... Would it be possible that undo is really undo, so that the status is removed from the list/history. Now we are creating a new state 'Rollback to New Access Request'. That is not good, and I consider it as the major flaw/bug for me in the logic of status update flow/history. I mean, undo should be really undo and get us one state back, not create a new state.

**Comment by hadiasghari** [comment]
@postdigital re your first point, wasn't the goal to reduce steps? 50% of companies respond before the deadline (and hopefully much more in the future). So it's more natural that the user just reports the interaction.

**Comment by postdigital** [comment]
I see your point, Hadi. 
In this case this step would be skipped and these would be all the options showing up already:

- I haven’t received anything
- I received (some) personal data
- I received an email/letter/call, but no data
- I received a statement that they don’t know me
- I received a letter of acknowledgement / confirmation
- I received a request of identity verification
- I received a request to be more specific
- I received a statement that they can’t verify my identity
- I received a request to fill in a form
- I received a request to visit them
- I received a request to call them
- I called/visited them
- I received a request to call/visit them, but I didn’t 
- Other
- I would like to undo this state
- I don’t want to continue

@mani47  - just a check - this would not bring problems with leaving the 'Awaiting response' mode?!

@hadiasghari The list of options is growing, but maybe we should skip a few in the Admin? Especially if we have the 'Other' option for the user out there...

**Comment by hadiasghari** [comment]
This issue is related to #110  and #121 , so I'll close this.
