### ISSUE TITLE
Error messages for login / signup

### ISSUE THREAD

**Issue by hadiasghari** [datarights/DataInSight#116]
(I will be updating this thread)

1. When clicking on Login button on the homepage, the following error (in red) is shown, and it's not clear why. The login works.
![di-screenshot-loginerror](https://user-images.githubusercontent.com/5025042/37567772-e12285e6-2acb-11e8-918d-3a9256fc54c6.png)

**Comment by hadiasghari** [comment]
2. When signing up with an email that already exists, the generic error message ("errors prohibited user from being save") should be simpler/clearer/more direct (e.g. "This email address is not available, try another"). Also shouldn't the error be red?

![di-screenshot-signuperr2](https://user-images.githubusercontent.com/5025042/37567842-ffa348a6-2acc-11e8-89a3-2c7337aa8612.png)

**Comment by hadiasghari** [comment]
3. no need to give message when login successful:

![di-screenshot-loginok](https://user-images.githubusercontent.com/5025042/37568257-ea4ff016-2ad2-11e8-919b-ea50a91ee7d8.png)

**Comment by hadiasghari** [comment]
@mani47 among above: 1st one is most critical; 2nd one can be moved to next milestone; 3rd one if simple solve, if not, next milestone.

**Comment by mani47** [comment]
Solved the first one. 

About 3rd one It's not very easy to fix since it's internal behavior of devise (user management) gem. But we can change the formatting and messages (2nd issue) You can change all the messages here:

https://github.com/datarights/DataInSight/blob/develop/config/locales/devise.en.yml

The one that you referring to is in line 63.

**Comment by mani47** [comment]
Fixed "no need to give message when login successful" as well.
