### ISSUE TITLE
Cookie notices

### ISSUE THREAD

**Issue by hadiasghari** [datarights/DataInSight#88]
We need to ensure we are compliant with cookie notice requirements.

**Comment by mani47** [comment]
According to this document (http://ec.europa.eu/ipg/basics/legal/cookies/index_en.htm) I think we are exempt from consent, because we are only using cookies for user-centric security and user interface customization (language).

> Cookies clearly exempt from consent according to the EU advisory body on data protection- WP29pdf include:
> 
> user‑input cookies (session-id) such as first‑party cookies to keep track of the user's input when filling online forms, shopping carts, etc., for the duration of a session or persistent cookies limited to a few hours in some cases
> authentication cookies, to identify the user once he has logged in, for the duration of a session
> user‑centric security cookies, used to detect authentication abuses, for a limited persistent duration
> multimedia content player cookies, used to store technical data to play back video or audio content, for the duration of a session
> load‑balancing cookies, for the duration of session
> user‑interface customisation cookies such as language or font preferences, for the duration of a session (or slightly longer)
> third‑party social plug‑in content‑sharing cookies, for logged‑in members of a social network.

**Comment by mani47** [comment]
Emphasis is on "duration of a session" and we do that except when user checks the "Remember me" checkbox in our login page: https://mapped-web.herokuapp.com/users/sign_in

I think we should ask for consent on that page and show the cookie notice when user checks the remember me box, what do you think?

**Comment by hadiasghari** [comment]
@mani47 for now possibly OK your point that we are not tracking.

@elsarebecat86, can you kindly check whether NL e-privacy law requires cookie-notice for non-tracking session-only cookies?

**Comment by elsarebecat86** [comment]
@hadiasghari, according to the article 17.1a of the telecommunication act, there are 2 exceptions in the NL e-privacy law for cookies-notices:

a. for the sole purpose of carrying out communication about an electronic communication network,
b. which is strictly necessary to provide the information society service requested by the subscriber or user or - provided this has no or minor impact on the privacy of the subscriber or user concerned - in order to obtain information about the quality or effectiveness of a delivered item information society service.

There is nothing else explicitly talking about non-tracking session cookies only. However, in my opinion, they might fall within these exceptions.

Here the link in dutch http://wetten.overheid.nl/BWBR0009950/2016-01-01#Hoofdstuk11_Paragraaf11.1_Artikel11.7a, but it can be easily translated with google.

**Comment by hadiasghari** [comment]
@elsarebecat86 thank you!

@mani47 so I'll close this issue for now; it will be something to make sure is included in our privacy policy.
